language: java
install: skip
os: osx
osx_image: xcode11
jdk: oraclejdk11
after_success:
    - ./gradlew publishMacosX64PublicationToBintrayRepository

#matrix:
#  include:
#    - os: linux
#      dist: bionic
#      jdk: oraclejdk11
#      after_success:
#        - ./gradlew publishAllPublicationsToBintrayRepository
#    - os: osx
#      osx_image: xcode11
#      jdk: oraclejdk11
#      after_success:
#        - ./gradlew compileMacosX64 --scan
#        - ./gradlew publishMacosPublicationToBintrayRepository
